# Generated by Django 4.1.7 on 2023-04-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OlxQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_keyword", models.TextField()),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="olxadvertisement",
            old_name="details",
            new_name="advertiser_name",
        ),
        migrations.RemoveField(
            model_name="olxadvertisement",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="olxadvertisement",
            name="name",
        ),
        migrations.AddField(
            model_name="olxadvertisement",
            name="advertiser_phone_number",
            field=models.CharField(default="232", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="olxadvertisement",
            name="location",
            field=models.TextField(default="wer"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="olxadvertisement",
            name="olx_id",
            field=models.CharField(default="2323", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="olxadvertisement",
            name="price",
            field=models.FloatField(default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="olxadvertisement",
            name="title",
            field=models.TextField(default="wertf"),
            preserve_default=False,
        ),
    ]
